# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{choco}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Anthony Heukmes"]
  s.date = %q{2010-07-22}
  s.default_executable = %q{choco}
  s.description = %q{Choco brings the MVC to the client side! It allows you to easily develop maintainable Rich Internet Applications using Javascript.}
  s.email = %q{anthony.heukmes@skynet.be}
  s.executables = ["choco"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "HISTORY",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "bin/choco",
     "choco.gemspec",
     "lib/choco.rb",
     "lib/choco/cli.rb",
     "lib/choco/dependency_manager.rb",
     "lib/choco/generators/app_generator.rb",
     "lib/choco/generators/controller_generator.rb",
     "lib/choco/generators/layout_generator.rb",
     "lib/choco/generators/model_generator.rb",
     "lib/choco/generators/plugin_generator.rb",
     "lib/choco/generators/scaffold_generator.rb",
     "lib/choco/generators/templates/Jimfile",
     "lib/choco/generators/templates/README.rdoc",
     "lib/choco/generators/templates/Rakefile",
     "lib/choco/generators/templates/application.css",
     "lib/choco/generators/templates/choco",
     "lib/choco/generators/templates/controllers/application_controller.js",
     "lib/choco/generators/templates/controllers/base_controller.js",
     "lib/choco/generators/templates/controllers/rest_controller.js",
     "lib/choco/generators/templates/help/commands",
     "lib/choco/generators/templates/help/generators",
     "lib/choco/generators/templates/helpers/application_helper.js",
     "lib/choco/generators/templates/index.html",
     "lib/choco/generators/templates/lib/plugin.js",
     "lib/choco/generators/templates/models/base.js",
     "lib/choco/generators/templates/views/edit.template",
     "lib/choco/generators/templates/views/index.template",
     "lib/choco/generators/templates/views/layout.js",
     "lib/choco/generators/templates/views/main/index.template",
     "lib/choco/generators/templates/views/new.template",
     "lib/choco/generators/templates/views/show.template",
     "spec/choco_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/ahe/choco}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A delicious Javascript web framework made in Belgium!}
  s.test_files = [
    "spec/choco_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jim>, [">= 0"])
      s.add_runtime_dependency(%q<fssm>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<jim>, [">= 0"])
      s.add_dependency(%q<fssm>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<jim>, [">= 0"])
    s.add_dependency(%q<fssm>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

